const x = 6;
println(x);

error err: let x = "hello";
if err != nil {
    println("error occurred:", err);
}

error err2 {
    let z = 7;
    fail("error message");
};

println(z); // z is defined because it's a local variable in the error section and
            // declared before the failing statement
println("err2", err2);
